# poetry run python main.py

# print('ola')

def funcao_com_erro_indice():
    lista = [1, 2, 3]
    print(lista[3]) # Índice 3 está fora dos limites (índices 0, 1 e 2)